export const Products = [
  {
    id: 1,
    img: "./images/airpods_max.jpg",
    text: "Apple Airpods Max",
    price: 699,
    type: "headphone",
    quantity: 1,
  },
  {
    id: 2,
    img: "./images/xm4.jpg",
    text: "Sony XM4",
    price: 399,
    type: "headphone",
    quantity: 1,
  },
  {
    id: 3,
    img: "./images/xm5.jpg",
    text: "Sony XM5",
    price: 499,
    type: "headphone",
    quantity: 1,
  },
  {
    id: 4,
    img: "./images/zen_hybrid.jpg",
    text: "Creative Zen Hybrid",
    price: 99,
    type: "headphone",
    quantity: 1,
  },
  {
    id: 5,
    img: "./images/airpods_pro.jpg",
    text: "Apple Airpods Pro 2",
    price: 199,
    type: "earphone",
    quantity: 1,
  },
  {
    id: 6,
    img: "./images/buds_pro.jpg",
    text: "Samsung Galaxy Buds Pro",
    price: 159,
    type: "earphone",
    quantity: 1,
  },
];
